[package]
name = "lsm-bigtest"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Runs a longer test with lots of data"
readme = "../README.md"

[dependencies]
clap.workspace = true
env_logger.workspace = true
tempfile.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full"] }
lsm = { workspace = true, features = ["snappy-compression", "bloom-filters"] }
